version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8011:80
      - 8012:1080
    volumes:
      - ./website:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp_sample
      WORDPRESS_MULTISITE: "false"
  db:
    image: mysql:5.7
    ports:
      - 33095:3306
    volumes:
      - ./export.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_sample
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass